add submodule update command to README for Building Raven
OpenTimelineIO/raven pull request #55
Opened 2024-08-28 00:29 UTC by ddouglas

2024-09-26 19:02 UTC, yaash45 commented
Hi @ddouglas! Not sure if you had a chance to see the discussion on #66, but it looks like we both have PRs to address the same issue.

I opted to supplement the introduction with a sentence indicating that a `--recursive` clone was necessary to build this project. I considered this sufficient for this use case. 

However, after reviewing your PR, I see the merit in adding the command to update submodules to the build steps like you did. This way, the user is building with the correct, initialized submodules each time.

Let me know your thoughts, but I am leaning towards accepting your changes and closing my PR (#66). Thanks!

2024-09-26 19:08 UTC, yaash45 requested changes
Small fix, but otherwise LGTM. It would be great to append the description with a line to close the related issue (I created one here #65). Thanks very much!

2024-09-26 19:08 UTC, yaash45 commented on README.md
> +  % git submodule update --init --recursive
I think the indenting is off here. It isn't rendering the README properly on GitHub because of it.

2024-09-28 06:19 UTC, jminor commented
This PR was folded into #66 - thanks to you both for making Raven's build instructions better :)

2024-09-28 06:19 UTC, closed without merging