Add media reference to inspector
OpenTimelineIO/raven pull request #68
Opened 2024-09-27 18:52 UTC by jspada200

This is a Work-In-Progress Pull Request meant to solve: https://github.com/OpenTimelineIO/raven/issues/62

### Changes

Main Changes:

- Add new section to inspector to view and modify Media References
- Supports MissingMediaReference, ExternalReference, and ImageSequenceReference classes
- Add attributes for:
- - Available Image Bounds
- - Available range
- - Target/Target URL base
- - Selected media reference
- - Metadata

Minor Changes:
- Vscode is changing the import order of implot
- Added the vscode config file to the gitignore for anyone else using vscode

Examples:

![2024-09-27 11 49 53](https://github.com/user-attachments/assets/6eb82f1e-76e9-46f9-abe7-e51dba97ae26)

![2024-09-27 11 49 00](https://github.com/user-attachments/assets/7e7980be-ae1c-436d-952f-58b7d34c7a56)

2024-09-27 22:18 UTC, jminor requested changes
This is looking great!

2024-09-27 22:18 UTC, jminor commented on inspector.cpp
> +            } else if (auto missing_ref = dynamic_cast<otio::MediaReference*>(selected_reference)) {
Did you mean `otio::MissingReference` here?

2024-09-27 22:18 UTC, jminor commented on inspector.cpp
> +            } else {
Could you add a Text label for the case where the media reference is `nullptr`?

2024-09-27 22:20 UTC, jminor commented
If you click the "Details" link next to the DCO and EasyCLA checks, there are instructions on how to get those resolved. Let us know if you get stuck or have questions about those.

2024-10-01 17:20 UTC, jspada200 commented
> If you click the "Details" link next to the DCO and EasyCLA checks, there are instructions on how to get those resolved. Let us know if you get stuck or have questions about those.

Thanks, I was able to figure out the DCO but my manager had me submit my name for the CLA. I am just waiting for them to let me know what needs to be done. 

Thanks!

2024-10-01 20:05 UTC, jminor commented
Ok, great. Let us know if there are questions about the CLA. I know some organizations can take a while to get those signed.

2024-10-03 17:38 UTC, jminor approved these changes
This is approved, just waiting for CLA.

2024-10-16 17:30 UTC, jspada200 commented
Just to follow up on this. Turns our that ILM does not have the CLAs setup for OTIO and needs to go through the process of getting those with Legal so it will be a bit longer this this and other PRs from ILM can be merged. Going to leave this PR open for now and stay on top of things here. 

Thanks!

2025-01-20 18:46 UTC, jspada200 commented
FYI.... Still waiting on CLA....

2025-05-16 07:20 UTC, timlehr commented
@jspada200 any update on the CLA?

2025-05-16 16:23 UTC, jspada200 commented
> @jspada200 any update on the CLA?

Still waiting 8 / on Legal/Security review.... Maybe my Open source days contribution this year will be resolving the merge conflicts and getting this in XD

2025-07-28 19:14 UTC, jminor commented
@jspada200 I believe the CLA has been signed now. Would you mind rebasing onto the latest main to see if the EasyCLA check will pass now?

2025-08-22 21:01 UTC, jminor commented
@jspada200 I confirmed that you are on the approved contributors list now. There are two steps remaining:
- You need to let GitHub know that you accept being added to that list: https://docs.linuxfoundation.org/lfx/easycla/v2-current/contributors/corporate-contributor#acknowledge-company-contribution
- You'll need to update some of your commits so they are all authored by the same email address, or just squash them into one.
Let me know if you need help with either of those. We're almost got this finished :)

2025-08-25 16:50 UTC, jspada200 commented
Thanks @jminor , Will give this a shot this week!

2025-08-25 18:09 UTC, jspada200 commented
I am not sure what is going on with the jspada200 and jspada200ilm account on github... Trying to figure it out so we can get passed this CLA thing! I did ask our CTO to approve the CLA again for jspada200....

2025-08-25 19:21 UTC, jminor commented
Some users are added to EasyCLA via their email vs their GitHub username. With the email, I'm not sure if that needs to match the email in each commit or the email on your GitHub user settings, or maybe both. I suspect that entering your GitHub username into EasyCLA would make it happy.

2025-08-25 19:57 UTC, jspada200 commented
> Some users are added to EasyCLA via their email vs their GitHub username. With the email, I'm not sure if that needs to match the email in each commit or the email on your GitHub user settings, or maybe both. I suspect that entering your GitHub username into EasyCLA would make it happy.

We did it @jminor !

2025-08-27 00:27 UTC, merged

2025-08-27 00:28 UTC, jminor commented
Woohoo! Thanks for the perseverance @jspada200 - the next one will be easier :)