Add drag and drop support for Windows
OpenTimelineIO/raven pull request #83
Opened 2024-11-05 16:24 UTC by ThomasWilshaw

As per #57 I've added drag and drop support for Windows. It seems to work okay on basic testing but I'm always a bit iffy about C pointers so please let me know if I've messed something up there.

If you drag a single file it loads correctly but if you drag several it triggers the existing code path for loading multiple files so any changes to that should work as expected on Windows

2024-11-05 17:42 UTC, meshula commented on main_win32.cpp
> +
the guts here become slightly more complex

```
        if (DragQueryFileW(hDrop, i, temp_filename, MAX_PATH)) {
            // Determine the required buffer size for the multi-byte string
            int buffer_size = WideCharToMultiByte(CP_UTF8, 0, temp_filename, -1, NULL, 0, NULL, NULL);

            // Allocate memory for the converted file name
            file_list[i] = (char*)malloc(buffer_size * sizeof(char));

            // Convert wide character filename to UTF-8
            WideCharToMultiByte(CP_UTF8, 0, temp_filename, -1, file_list[i], buffer_size, NULL, NULL);
        }
```

2024-11-05 17:42 UTC, meshula commented on main_win32.cpp
> +
add
```
   wchar_t temp_filename[MAX_PATH];
```

2024-11-05 17:43 UTC, meshula requested changes
This is very cool, thanks :) Small request though.

2024-11-05 17:43 UTC, meshula commented on main_win32.cpp
> +        UINT count = DragQueryFileA(hDrop, -1, NULL, 0);
could we switch this to W please, and the char** to wchar_t** as necessary? I haven't check the rest of main to find out if there's more ANSI to WIDE conversion necessary, but we could start here.

2024-11-05 18:08 UTC, darbyjohnston commented on main_win32.cpp
> +        UINT count = DragQueryFileA(hDrop, -1, NULL, 0);
Both `src/opentimelineio/serialization.cpp` and `src/opentimelineio/deserialization.cpp` use `MultiByteToWideChar()` for opening files.

2024-11-06 10:49 UTC, ThomasWilshaw commented on main_win32.cpp
> +        UINT count = DragQueryFileA(hDrop, -1, NULL, 0);
Am I right in thinking `file_list` should remain as `char` as we're converting UTF characters in `temp_filename` into `char`s with `WideCharToMultiByte`?

2024-11-07 02:18 UTC, meshula commented on main_win32.cpp
> +        UINT count = DragQueryFileA(hDrop, -1, NULL, 0);
Yes, that's right.

2024-11-08 11:18 UTC, ThomasWilshaw commented
I think that's all your comments resolved, let me know if I missed anything

2024-11-09 08:27 UTC, meshula approved these changes
lgtm!! Thanks :)

2024-11-09 21:47 UTC, merged

2024-11-09 21:47 UTC, jminor commented
Thanks @ThomasWilshaw !